name: flutter_app2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=1.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #工具类 时间、日期、日志
  common_utils: '^1.1.1'
  #弹框
  rflutter_alert: ^1.0.2
  #动画
  nima: '^1.0.0'
  # 统计图表
  charts_flutter: '^0.4.0'

  #加载动画
  flutter_spinkit: "^3.1.0"
  #图片选择 image_picker：0.4.12 + 1 避免android X的兼容问题
  image_picker: ^0.4.12
  # 权限申请
  permission: ^0.1.1

  english_words: ^3.1.0
  http: ^0.12.0+1
  shared_preferences: "^0.4.2"
  transparent_image: "^0.1.0"
  flutter_swiper : "^1.1.4"
  path_provider: ^0.5.0+1
  cached_network_image: "0.6.0"
  sqflite: ^1.1.0
  pull_to_refresh: "^1.1.5"
  video_player: "0.6.1"
  collection: 1.15.0
  device_info: 0.2.1
  intl: 0.15.7
  connectivity: 0.3.1
  fluttertoast: ^3.0.4
  shimmer: ^0.0.4
  flutter_staggered_grid_view:
  flutter_slidable: "^0.4.9"
  scoped_model: 1.0.1
  flutter_webview_plugin: ^0.2.1+2
  flutter_inappbrowser: ^0.6.0

  #微信
  fluwx: ^0.6.2

  #shop
  json_serializable: ^2.0.0


#  #高德地图
#  amap_base:
#    git:
#      url: https://github.com/yohom/amap_base_flutter.git
#      ref: android-support-library
#      path: base

   #极光推送
  jpush_flutter: ^0.0.11




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
    - raw/
